name: .NET Core
# Trigger event on a push or pull request
on: [push, pull_request]

# Jobs that run in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       include:
        - dotnet-version: '3.1.x'
          tfm: 'netcoreapp3.1'
        - dotnet-version: '5.0.x'
          tfm: 'net5.0'
        - dotnet-version: '6.0.x'
          tfm: 'net6.0'
    # Steps that run sequentially
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Install dependencies
      run: dotnet restore -p:TargetFramework=${{ matrix.tfm }}
      
    - name: Build
      run: dotnet build --configuration Release src/HybridModelBinding --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal -f=${{ matrix.tfm }}
